### PR TITLE
Topo dist histograms

### PR DESCRIPTION
**Pull request by MustafaMustafa**
@GuannanXie 
Please review and merge.

### CODE REVIEW

**Comment by GuannanXie** [comment]
two cents,
1, for "usedTriplet", this implement is especial for Dpm ( insert twice), Does this need for Lc?
2, hybrid pid for Dpm is ok, not sure, can we get signal for Lc.

**Comment by MustafaMustafa** [comment]
Hi @GuannanXie , 

Thank you very much. Please see the fix for you first point at in fb97b9e0afec95aa9421fd9e46ebd19547b7e283. 

I will wait your confirmation for the proton PID.

**Comment by GuannanXie** [comment]
@MustafaMustafa 
It would be good to try strict PID for Kaon and Proton with this setup of cuts. (For Lc)
I checked the ntuple, the significance difference is from 3.5 to 5.5.

**Comment by MustafaMustafa** [comment]
@GuannanXie 
Implemented.

**Pull request merged**
